name: CI

on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        argument: build
  build:
    runs-on: [self-hosted]
    steps:
      - name: build
        run: ./gradlew build
