name: CI

on: [push]

jobs:
  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ./gradlew test
  build:
    runs-on: [self-hosted]
    steps:
      - name: build
        run: ./gradlew build
